/**
 * Données fictives réalistes pour le suivi de colis FedEx
 * Trajet : France → Autriche (Colis actuellement à l'agence FedEx en Autriche)
 */

import type {
  ParcelInfo,
  StatCard,
  Notification,
  Document,
  FeeSummary,
  TimelineEvent,
} from "./types";

// ─── Timeline Events ───────────────────────────────────────────────
export const timelineEvents: TimelineEvent[] = [
  {
    id: "evt-1",
    date: "2026-07-11",
    time: "09:15",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    facility: "FedEx Charles de Gaulle Hub",
    status: "created",
    description: "Expédition créée – Étiquette d'envoi générée",
    completed: true,
    icon: "FileText",
  },
  {
    id: "evt-2",
    date: "2026-07-11",
    time: "14:30",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    facility: "FedEx Station Paris-Bercy",
    status: "picked_up",
    description: "Colis récupéré chez l'expéditeur",
    completed: true,
    icon: "PackageCheck",
  },
  {
    id: "evt-3",
    date: "2026-07-11",
    time: "19:45",
    city: "Roissy-en-France",
    country: "France",
    countryCode: "FR",
    facility: "FedEx Hub Roissy CDG",
    status: "in_transit",
    description: "Arrivé au centre de tri FedEx – Traitement en cours",
    completed: true,
    icon: "Warehouse",
  },
  {
    id: "evt-4",
    date: "2026-07-11",
    time: "22:10",
    city: "Roissy-en-France",
    country: "France",
    countryCode: "FR",
    facility: "FedEx Hub Roissy CDG – Douanes",
    status: "customs",
    description: "Contrôle douanier export – Dédouanement effectué",
    completed: true,
    icon: "Shield",
  },
  {
    id: "evt-5",
    date: "2026-07-12",
    time: "01:30",
    city: "Roissy-en-France",
    country: "France",
    countryCode: "FR",
    facility: "FedEx Hub Roissy CDG",
    status: "in_transit",
    description: "Départ du hub – En transit vers l'Autriche",
    completed: true,
    icon: "Plane",
  },
  {
    id: "evt-6",
    date: "2026-07-12",
    time: "05:20",
    city: "Strasbourg",
    country: "France",
    countryCode: "FR",
    facility: "FedEx Station Strasbourg",
    status: "in_transit",
    description: "Escale au centre de transit – Transfert en cours",
    completed: true,
    icon: "Truck",
  },
  {
    id: "evt-7",
    date: "2026-07-12",
    time: "09:45",
    city: "Munich",
    country: "Allemagne",
    countryCode: "DE",
    facility: "FedEx Hub München",
    status: "in_transit",
    description: "Arrivé au hub FedEx de Munich – Transit international",
    completed: true,
    icon: "MapPin",
  },
  {
    id: "evt-8",
    date: "2026-07-12",
    time: "12:15",
    city: "Salzbourg",
    country: "Autriche",
    countryCode: "AT",
    facility: "FedEx Station Salzburg",
    status: "arrived_destination",
    description: "Arrivé dans le pays de destination – Autriche",
    completed: true,
    icon: "Flag",
  },
  {
    id: "evt-9",
    date: "2026-07-12",
    time: "14:00",
    city: "Salzbourg",
    country: "Autriche",
    countryCode: "AT",
    facility: "FedEx Station Salzburg – Douanes",
    status: "customs",
    description: "Contrôle douanier import – Frais de douane à régler par le destinataire",
    completed: true,
    icon: "ShieldAlert",
  },
  // ─── 900€ PAYÉ (VERT) ✅ ───────────────────────────────────────────
  {
    id: "evt-10",
    date: "2026-07-12",
    time: "16:30",
    city: "Salzbourg",
    country: "Autriche",
    countryCode: "AT",
    facility: "FedEx Distribution Center Salzburg",
    status: "distribution_center",
    description:
      "Colis au centre de distribution FedEx – Frais de douane réglés (900,00 €)",
    completed: true,
    icon: "Building",
    paid: true,
  },
  // ─── 721€ EN ATTENTE (ORANGE) 🟠 ──────────────────────────────────
  {
    id: "evt-11",
    date: "2026-07-14",
    time: "08:30",
    city: "Salzbourg",
    country: "Autriche",
    countryCode: "AT",
    facility: "FedEx Distribution Center Salzburg",
    status: "pending_payment",
    description:
      "Frais de transport sécurisé des espèces – En attente du règlement (721,00 €)",
    completed: true,
    icon: "ShieldAlert",
  },
  {
    id: "evt-12",
    date: "",
    time: "",
    city: "Krispl",
    country: "Autriche",
    countryCode: "AT",
    facility: "",
    status: "out_for_delivery",
    description: "En cours de livraison",
    completed: false,
    icon: "TruckIcon",
  },
  {
    id: "evt-13",
    date: "",
    time: "",
    city: "Krispl",
    country: "Autriche",
    countryCode: "AT",
    facility: "",
    status: "delivered",
    description: "Livré",
    completed: false,
    icon: "CheckCircle",
  },
];

// ─── Parcel Information ─────────────────────────────────────────────
export const parcelInfo: ParcelInfo = {
  trackingNumber: "7721 4568 3901",
  status: "distribution_center",
  statusLabel: "Au centre de distribution – Frais en attente",
  serviceType: "FedEx International Priority",
  shipDate: "2026-07-11",
  estimatedDelivery: "2026-07-14",
  weight: "12.5 kg",
  numberOfParcels: 1,
  dimensions: "60 × 40 × 35 cm",
  contents: "Argent (espèces)",
  declaredValue: "2 450,00 €",
  insurance: "Couverture complète – 3 000,00 €",
  signatureRequired: true,
  progressPercent: 78,
  sender: {
    name: "Martin Lefèvre",
    company: "-",
    address: "47 Rue de la République",
    city: "Lyon",
    postalCode: "69002",
    country: "France",
    countryCode: "FR",
    phone: "+33 4 72 56 89 01",
    email: "m.lefevremartin@gmail.com",
  },
  recipient: {
    name: "Leo Auer",
    company: "-",
    address: "Gaissau 112",
    city: "5425 Krispl",
    postalCode: "5425",
    country: "Autriche",
    countryCode: "AT",
    phone: "+43 664 4881150",
    email: "Auer.leo.holz@gmail.com",
  },
  timeline: timelineEvents,
};

// ─── Stats Cards ────────────────────────────────────────────────────
export const statsCards: StatCard[] = [
  {
    id: "stat-1",
    label: "totalParcels",
    value: 1248,
    change: 12.5,
    icon: "Package",
    color: "#4A1D96",
    bgColor: "bg-purple-50",
  },
  {
    id: "stat-2",
    label: "inTransit",
    value: 342,
    change: 8.3,
    icon: "Truck",
    color: "#FF6600",
    bgColor: "bg-orange-50",
  },
  {
    id: "stat-3",
    label: "delivered",
    value: 856,
    change: 15.2,
    icon: "CheckCircle",
    color: "#16A34A",
    bgColor: "bg-green-50",
  },
  {
    id: "stat-4",
    label: "pending",
    value: 28,
    change: -3.1,
    icon: "Clock",
    color: "#EAB308",
    bgColor: "bg-yellow-50",
  },
  {
    id: "stat-5",
    label: "delayed",
    value: 15,
    change: -7.4,
    icon: "AlertTriangle",
    color: "#DC2626",
    bgColor: "bg-red-50",
  },
  {
    id: "stat-6",
    label: "cancelled",
    value: 7,
    change: -12.0,
    icon: "XCircle",
    color: "#6B7280",
    bgColor: "bg-gray-50",
  },
];

// ─── Notifications ──────────────────────────────────────────────────
export const notifications: Notification[] = [
  {
    id: "notif-0",
    date: "2026-07-14",
    time: "08:35",
    message:
      "Nouveaux frais détectés : Frais de transport sécurisé des espèces de 721,00 € à régler pour débloquer la livraison.",
    priority: "high",
    read: false,
  },
  {
    id: "notif-1",
    date: "2026-07-12",
    time: "16:35",
    message:
      "Les frais de douane de 900,00 € ont été réglés avec succès. Merci !",
    priority: "info",
    read: true,
  },
  {
    id: "notif-2",
    date: "2026-07-12",
    time: "14:05",
    message:
      "Contrôle douanier import terminé à Salzbourg. Frais de dédouanement calculés.",
    priority: "medium",
    read: true,
  },
  {
    id: "notif-3",
    date: "2026-07-12",
    time: "12:20",
    message:
      "Votre colis est arrivé en Autriche – FedEx Station Salzburg.",
    priority: "info",
    read: true,
  },
  {
    id: "notif-4",
    date: "2026-07-12",
    time: "09:50",
    message:
      "Transit international : colis arrivé au hub FedEx de Munich, Allemagne.",
    priority: "info",
    read: true,
  },
  {
    id: "notif-5",
    date: "2026-07-12",
    time: "01:35",
    message:
      "Votre colis a quitté le hub FedEx de Roissy CDG en direction de l'Autriche.",
    priority: "info",
    read: true,
  },
  {
    id: "notif-6",
    date: "2026-07-11",
    time: "14:35",
    message:
      "Colis récupéré avec succès chez l'expéditeur à Paris.",
    priority: "low",
    read: true,
  },
];

// ─── Documents ──────────────────────────────────────────────────────
export const documents: Document[] = [
  {
    id: "doc-1",
    name: "Facture commerciale",
    type: "PDF",
    size: "245 KB",
    icon: "FileText",
  },
  {
    id: "doc-2",
    name: "Bon d'expédition",
    type: "PDF",
    size: "128 KB",
    icon: "FileText",
  },
  {
    id: "doc-3",
    name: "Preuve de dépôt",
    type: "PDF",
    size: "89 KB",
    icon: "FileCheck",
  },
  {
    id: "doc-4",
    name: "Preuve de livraison (POD)",
    type: "PDF",
    size: "—",
    icon: "FileCheck",
  },
  {
    id: "doc-5",
    name: "Documents douaniers",
    type: "PDF",
    size: "312 KB",
    icon: "FileWarning",
  },
];

// ─── Fees & Charges ─────────────────────────────────────────────────
export const feeSummary: FeeSummary = {
  fees: [
    {
      id: "fee-1",
      label: "Droits de douane (Zollgebühren)",
      amount: 392.0,
      description:
        "Droits de douane à l'importation conformément au tarif douanier commun de l'UE – Taux applicable : 4,7 % sur la valeur déclarée",
      category: "customs",
      status: "validated",
    },
    {
      id: "fee-2",
      label: "TVA à l'importation (Einfuhrumsatzsteuer – EUSt)",
      amount: 380.0,
      description:
        "TVA autrichienne à l'importation au taux de 20 % conformément à l'article 26 UStG",
      category: "tax",
      status: "validated",
    },
    {
      id: "fee-3",
      label: "Frais de dédouanement FedEx",
      amount: 55.0,
      description:
        "Frais de gestion et traitement du dossier de dédouanement par FedEx Trade Networks",
      category: "service",
      status: "validated",
    },
    {
      id: "fee-4",
      label: "Frais de manutention et entreposage",
      amount: 38.0,
      description:
        "Frais de manutention en entrepôt sous douane – Stockage temporaire au centre FedEx Salzburg",
      category: "handling",
      status: "validated",
    },
    {
      id: "fee-5",
      label: "Frais d'avance de fonds (Disbursement Fee)",
      amount: 35.0,
      description:
        "Commission pour l'avance des droits et taxes par FedEx au nom du destinataire",
      category: "service",
      status: "validated",
    },
    // ─── Nouveau frais de 721€ en attente ─────────────────────────────
    {
      id: "fee-6",
      label: "Frais de transport sécurisé des espèces",
      amount: 721,
      description:
        "Frais de transport et manutention sécurisée des espèces (Cash-in-Transit). Service spécialisé pour le transport de valeurs monétaires avec escorte et assurance renforcée.",
      category: "service",
      status: "pending",
    },
  ],
  validatedTotal: 900.0,
  pendingTotal: 721,
  totalAmount: 1621,
  currency: "EUR",
  dueDate: "2026-07-16",
  paymentStatus: "pending",
  recipientName: "Leo Auer",
};

// ─── Map Route Coordinates (simplified) ─────────────────────────────
export const routePoints = [
  { lat: 48.8566, lng: 2.3522, label: "Paris, France", type: "origin" as const },
  { lat: 48.7252, lng: 2.3590, label: "Roissy CDG, France", type: "stopover" as const },
  { lat: 48.5734, lng: 7.7521, label: "Strasbourg, France", type: "stopover" as const },
  { lat: 48.1351, lng: 11.582, label: "Munich, Allemagne", type: "stopover" as const },
  { lat: 47.8095, lng: 13.055, label: "Salzbourg, Autriche", type: "current" as const },
  { lat: 47.7167, lng: 13.15, label: "Krispl, Autriche", type: "destination" as const },
];